// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ReadFileHandlerFunc turns a function with the right signature into a read file handler
type ReadFileHandlerFunc func(ReadFileParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ReadFileHandlerFunc) Handle(params ReadFileParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ReadFileHandler interface for that can handle valid read file params
type ReadFileHandler interface {
	Handle(ReadFileParams, interface{}) middleware.Responder
}

// NewReadFile creates a new http.Handler for the read file operation
func NewReadFile(ctx *middleware.Context, handler ReadFileHandler) *ReadFile {
	return &ReadFile{Context: ctx, Handler: handler}
}

/*ReadFile swagger:route GET /readFile Storage readFile

Download a file

Streaming a file contents to the client

*/
type ReadFile struct {
	Context *middleware.Context
	Handler ReadFileHandler
}

func (o *ReadFile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewReadFileParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
