// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "storage.futuremobile.net/m/v2/internal/pkg/models"
)

// ReadFolderOKCode is the HTTP code returned for type ReadFolderOK
const ReadFolderOKCode int = 200

/*ReadFolderOK List of files or folders

swagger:response readFolderOK
*/
type ReadFolderOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetStorageFolderResponse `json:"body,omitempty"`
}

// NewReadFolderOK creates ReadFolderOK with default headers values
func NewReadFolderOK() *ReadFolderOK {

	return &ReadFolderOK{}
}

// WithPayload adds the payload to the read folder o k response
func (o *ReadFolderOK) WithPayload(payload *models.GetStorageFolderResponse) *ReadFolderOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the read folder o k response
func (o *ReadFolderOK) SetPayload(payload *models.GetStorageFolderResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReadFolderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReadFolderBadRequestCode is the HTTP code returned for type ReadFolderBadRequest
const ReadFolderBadRequestCode int = 400

/*ReadFolderBadRequest Bad Request

swagger:response readFolderBadRequest
*/
type ReadFolderBadRequest struct {
}

// NewReadFolderBadRequest creates ReadFolderBadRequest with default headers values
func NewReadFolderBadRequest() *ReadFolderBadRequest {

	return &ReadFolderBadRequest{}
}

// WriteResponse to the client
func (o *ReadFolderBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// ReadFolderForbiddenCode is the HTTP code returned for type ReadFolderForbidden
const ReadFolderForbiddenCode int = 403

/*ReadFolderForbidden Forbidden

swagger:response readFolderForbidden
*/
type ReadFolderForbidden struct {
}

// NewReadFolderForbidden creates ReadFolderForbidden with default headers values
func NewReadFolderForbidden() *ReadFolderForbidden {

	return &ReadFolderForbidden{}
}

// WriteResponse to the client
func (o *ReadFolderForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
