// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "futuremobile.net/m/v2/internal/pkg/models"
)

// StorageReadFolderOKCode is the HTTP code returned for type StorageReadFolderOK
const StorageReadFolderOKCode int = 200

/*StorageReadFolderOK List of files or folders

swagger:response storageReadFolderOK
*/
type StorageReadFolderOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetStorageFolderResponse `json:"body,omitempty"`
}

// NewStorageReadFolderOK creates StorageReadFolderOK with default headers values
func NewStorageReadFolderOK() *StorageReadFolderOK {

	return &StorageReadFolderOK{}
}

// WithPayload adds the payload to the storage read folder o k response
func (o *StorageReadFolderOK) WithPayload(payload *models.GetStorageFolderResponse) *StorageReadFolderOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the storage read folder o k response
func (o *StorageReadFolderOK) SetPayload(payload *models.GetStorageFolderResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StorageReadFolderOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// StorageReadFolderBadRequestCode is the HTTP code returned for type StorageReadFolderBadRequest
const StorageReadFolderBadRequestCode int = 400

/*StorageReadFolderBadRequest Bad Request

swagger:response storageReadFolderBadRequest
*/
type StorageReadFolderBadRequest struct {
}

// NewStorageReadFolderBadRequest creates StorageReadFolderBadRequest with default headers values
func NewStorageReadFolderBadRequest() *StorageReadFolderBadRequest {

	return &StorageReadFolderBadRequest{}
}

// WriteResponse to the client
func (o *StorageReadFolderBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// StorageReadFolderForbiddenCode is the HTTP code returned for type StorageReadFolderForbidden
const StorageReadFolderForbiddenCode int = 403

/*StorageReadFolderForbidden Forbidden

swagger:response storageReadFolderForbidden
*/
type StorageReadFolderForbidden struct {
}

// NewStorageReadFolderForbidden creates StorageReadFolderForbidden with default headers values
func NewStorageReadFolderForbidden() *StorageReadFolderForbidden {

	return &StorageReadFolderForbidden{}
}

// WriteResponse to the client
func (o *StorageReadFolderForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
