// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// StorageWriteFileHandlerFunc turns a function with the right signature into a storage write file handler
type StorageWriteFileHandlerFunc func(StorageWriteFileParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn StorageWriteFileHandlerFunc) Handle(params StorageWriteFileParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// StorageWriteFileHandler interface for that can handle valid storage write file params
type StorageWriteFileHandler interface {
	Handle(StorageWriteFileParams, interface{}) middleware.Responder
}

// NewStorageWriteFile creates a new http.Handler for the storage write file operation
func NewStorageWriteFile(ctx *middleware.Context, handler StorageWriteFileHandler) *StorageWriteFile {
	return &StorageWriteFile{Context: ctx, Handler: handler}
}

/*StorageWriteFile swagger:route POST /writeFile Storage storageWriteFile

Upload files to the storage

Upload multiple files into the given path (folder)

*/
type StorageWriteFile struct {
	Context *middleware.Context
	Handler StorageWriteFileHandler
}

func (o *StorageWriteFile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewStorageWriteFileParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
