// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// StorageReadFolderHandlerFunc turns a function with the right signature into a storage read folder handler
type StorageReadFolderHandlerFunc func(StorageReadFolderParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn StorageReadFolderHandlerFunc) Handle(params StorageReadFolderParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// StorageReadFolderHandler interface for that can handle valid storage read folder params
type StorageReadFolderHandler interface {
	Handle(StorageReadFolderParams, interface{}) middleware.Responder
}

// NewStorageReadFolder creates a new http.Handler for the storage read folder operation
func NewStorageReadFolder(ctx *middleware.Context, handler StorageReadFolderHandler) *StorageReadFolder {
	return &StorageReadFolder{Context: ctx, Handler: handler}
}

/*StorageReadFolder swagger:route GET /readFolder Storage storageReadFolder

Get a list of files and folders

Get a list of files and folders in a given path (folder)

*/
type StorageReadFolder struct {
	Context *middleware.Context
	Handler StorageReadFolderHandler
}

func (o *StorageReadFolder) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewStorageReadFolderParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
