// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStorageReadFolderParams creates a new StorageReadFolderParams object
// no default values defined in spec.
func NewStorageReadFolderParams() StorageReadFolderParams {

	return StorageReadFolderParams{}
}

// StorageReadFolderParams contains all the bound params for the storage read folder operation
// typically these are obtained from a http.Request
//
// swagger:parameters storageReadFolder
type StorageReadFolderParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*A path of target folder
	  In: query
	*/
	R *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewStorageReadFolderParams() beforehand.
func (o *StorageReadFolderParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qR, qhkR, _ := qs.GetOK("r")
	if err := o.bindR(qR, qhkR, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindR binds and validates parameter R from query.
func (o *StorageReadFolderParams) bindR(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.R = &raw

	return nil
}
