// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "futuremobile.net/m/v2/internal/pkg/models"
)

// StorageWriteFileOKCode is the HTTP code returned for type StorageWriteFileOK
const StorageWriteFileOKCode int = 200

/*StorageWriteFileOK Status of file uploading

swagger:response storageWriteFileOK
*/
type StorageWriteFileOK struct {

	/*
	  In: Body
	*/
	Payload models.StorageResponse `json:"body,omitempty"`
}

// NewStorageWriteFileOK creates StorageWriteFileOK with default headers values
func NewStorageWriteFileOK() *StorageWriteFileOK {

	return &StorageWriteFileOK{}
}

// WithPayload adds the payload to the storage write file o k response
func (o *StorageWriteFileOK) WithPayload(payload models.StorageResponse) *StorageWriteFileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the storage write file o k response
func (o *StorageWriteFileOK) SetPayload(payload models.StorageResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StorageWriteFileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.StorageResponse{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// StorageWriteFileBadRequestCode is the HTTP code returned for type StorageWriteFileBadRequest
const StorageWriteFileBadRequestCode int = 400

/*StorageWriteFileBadRequest Bad Request

swagger:response storageWriteFileBadRequest
*/
type StorageWriteFileBadRequest struct {
}

// NewStorageWriteFileBadRequest creates StorageWriteFileBadRequest with default headers values
func NewStorageWriteFileBadRequest() *StorageWriteFileBadRequest {

	return &StorageWriteFileBadRequest{}
}

// WriteResponse to the client
func (o *StorageWriteFileBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// StorageWriteFileForbiddenCode is the HTTP code returned for type StorageWriteFileForbidden
const StorageWriteFileForbiddenCode int = 403

/*StorageWriteFileForbidden Forbidden

swagger:response storageWriteFileForbidden
*/
type StorageWriteFileForbidden struct {
}

// NewStorageWriteFileForbidden creates StorageWriteFileForbidden with default headers values
func NewStorageWriteFileForbidden() *StorageWriteFileForbidden {

	return &StorageWriteFileForbidden{}
}

// WriteResponse to the client
func (o *StorageWriteFileForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// StorageWriteFileInternalServerErrorCode is the HTTP code returned for type StorageWriteFileInternalServerError
const StorageWriteFileInternalServerErrorCode int = 500

/*StorageWriteFileInternalServerError Internal Server Error

swagger:response storageWriteFileInternalServerError
*/
type StorageWriteFileInternalServerError struct {
}

// NewStorageWriteFileInternalServerError creates StorageWriteFileInternalServerError with default headers values
func NewStorageWriteFileInternalServerError() *StorageWriteFileInternalServerError {

	return &StorageWriteFileInternalServerError{}
}

// WriteResponse to the client
func (o *StorageWriteFileInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
