// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"
)

// StorageReadFileOKCode is the HTTP code returned for type StorageReadFileOK
const StorageReadFileOKCode int = 200

/*StorageReadFileOK download a file

swagger:response storageReadFileOK
*/
type StorageReadFileOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewStorageReadFileOK creates StorageReadFileOK with default headers values
func NewStorageReadFileOK() *StorageReadFileOK {

	return &StorageReadFileOK{}
}

// WithPayload adds the payload to the storage read file o k response
func (o *StorageReadFileOK) WithPayload(payload io.ReadCloser) *StorageReadFileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the storage read file o k response
func (o *StorageReadFileOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *StorageReadFileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// StorageReadFileBadRequestCode is the HTTP code returned for type StorageReadFileBadRequest
const StorageReadFileBadRequestCode int = 400

/*StorageReadFileBadRequest Bad Request

swagger:response storageReadFileBadRequest
*/
type StorageReadFileBadRequest struct {
}

// NewStorageReadFileBadRequest creates StorageReadFileBadRequest with default headers values
func NewStorageReadFileBadRequest() *StorageReadFileBadRequest {

	return &StorageReadFileBadRequest{}
}

// WriteResponse to the client
func (o *StorageReadFileBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// StorageReadFileForbiddenCode is the HTTP code returned for type StorageReadFileForbidden
const StorageReadFileForbiddenCode int = 403

/*StorageReadFileForbidden Forbidden

swagger:response storageReadFileForbidden
*/
type StorageReadFileForbidden struct {
}

// NewStorageReadFileForbidden creates StorageReadFileForbidden with default headers values
func NewStorageReadFileForbidden() *StorageReadFileForbidden {

	return &StorageReadFileForbidden{}
}

// WriteResponse to the client
func (o *StorageReadFileForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}
