// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// WriteFileHandlerFunc turns a function with the right signature into a write file handler
type WriteFileHandlerFunc func(WriteFileParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn WriteFileHandlerFunc) Handle(params WriteFileParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// WriteFileHandler interface for that can handle valid write file params
type WriteFileHandler interface {
	Handle(WriteFileParams, interface{}) middleware.Responder
}

// NewWriteFile creates a new http.Handler for the write file operation
func NewWriteFile(ctx *middleware.Context, handler WriteFileHandler) *WriteFile {
	return &WriteFile{Context: ctx, Handler: handler}
}

/*WriteFile swagger:route POST /writeFile Storage writeFile

Upload files to the storage

Upload multiple files into the given path (folder)

*/
type WriteFile struct {
	Context *middleware.Context
	Handler WriteFileHandler
}

func (o *WriteFile) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewWriteFileParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
