// Code generated by go-swagger; DO NOT EDIT.

package storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "storage.futuremobile.net/m/v2/internal/pkg/models"
)

// WriteFileOKCode is the HTTP code returned for type WriteFileOK
const WriteFileOKCode int = 200

/*WriteFileOK Status of file uploading

swagger:response writeFileOK
*/
type WriteFileOK struct {

	/*
	  In: Body
	*/
	Payload models.StorageResponse `json:"body,omitempty"`
}

// NewWriteFileOK creates WriteFileOK with default headers values
func NewWriteFileOK() *WriteFileOK {

	return &WriteFileOK{}
}

// WithPayload adds the payload to the write file o k response
func (o *WriteFileOK) WithPayload(payload models.StorageResponse) *WriteFileOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the write file o k response
func (o *WriteFileOK) SetPayload(payload models.StorageResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *WriteFileOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.StorageResponse{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// WriteFileBadRequestCode is the HTTP code returned for type WriteFileBadRequest
const WriteFileBadRequestCode int = 400

/*WriteFileBadRequest Bad Request

swagger:response writeFileBadRequest
*/
type WriteFileBadRequest struct {
}

// NewWriteFileBadRequest creates WriteFileBadRequest with default headers values
func NewWriteFileBadRequest() *WriteFileBadRequest {

	return &WriteFileBadRequest{}
}

// WriteResponse to the client
func (o *WriteFileBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// WriteFileForbiddenCode is the HTTP code returned for type WriteFileForbidden
const WriteFileForbiddenCode int = 403

/*WriteFileForbidden Forbidden

swagger:response writeFileForbidden
*/
type WriteFileForbidden struct {
}

// NewWriteFileForbidden creates WriteFileForbidden with default headers values
func NewWriteFileForbidden() *WriteFileForbidden {

	return &WriteFileForbidden{}
}

// WriteResponse to the client
func (o *WriteFileForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(403)
}

// WriteFileInternalServerErrorCode is the HTTP code returned for type WriteFileInternalServerError
const WriteFileInternalServerErrorCode int = 500

/*WriteFileInternalServerError Internal Server Error

swagger:response writeFileInternalServerError
*/
type WriteFileInternalServerError struct {
}

// NewWriteFileInternalServerError creates WriteFileInternalServerError with default headers values
func NewWriteFileInternalServerError() *WriteFileInternalServerError {

	return &WriteFileInternalServerError{}
}

// WriteResponse to the client
func (o *WriteFileInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
