// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Storage
This is a API specification for [futuremobile.net](https://futuremobile.net)


    Schemes:
      https
    Host: storage.futuremobile.net
    BasePath: /
    Version: 0.0.1

    Consumes:
    - multipart/form-data

    Produces:
    - application/json
    - application/octect-stream
    - text/plain

swagger:meta
*/
package restapi
