// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// BadRequest bad request
// swagger:model badRequest
type BadRequest string

// Validate validates this bad request
func (m BadRequest) Validate(formats strfmt.Registry) error {
	return nil
}
