// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// Created created
// swagger:model created
type Created string

// Validate validates this created
func (m Created) Validate(formats strfmt.Registry) error {
	return nil
}
