// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// InternalServerError internal server error
// swagger:model internalServerError
type InternalServerError string

// Validate validates this internal server error
func (m InternalServerError) Validate(formats strfmt.Registry) error {
	return nil
}
