// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// NotFound not found
// swagger:model notFound
type NotFound string

// Validate validates this not found
func (m NotFound) Validate(formats strfmt.Registry) error {
	return nil
}
