// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// RedirectURL redirect URL
// swagger:model redirectURL
type RedirectURL string

// Validate validates this redirect URL
func (m RedirectURL) Validate(formats strfmt.Registry) error {
	return nil
}
